### ISSUE TITLE
Can't install via coccapods

### ISSUE THREAD

**Issue by dberroa** [vinceyuan/VYNFCKit#1]
I tried following the directions stated in the readme and I get the following error then I try installing the library from coccapods.

`[!] Unable to find a specification for `VYNFCKit`
`

**Comment by vinceyuan** [comment]
It's there. You can open https://cocoapods.org/pods/VYNFCKit
Run `pod repo update` to update your cocoapods repo and try `pod install` again.

**Comment by dberroa** [comment]
Oops, sorry about that. The repo update fixed it. Guess I still have some stuff to learn about coccapods.

Can't wait to try this out! I was having trouble getting NFC in my iOS 11 app.

**Comment by vinceyuan** [comment]
No problem. Check the example first.
Welcome to report any issue.
