### ISSUE TITLE
class "NFFieldNotification" not loaded or does not exist

### ISSUE THREAD

**Issue by ulian-onua** [vinceyuan/VYNFCKit#13]
I need to be able to read NFC tags that are written by Android device.

I found a video where it is shown that is is possible to do -> https://www.youtube.com/watch?v=w1bfTJar2NY

I am trying to scan NFC NDEF tag from Android device which writes NFC tag.

Here a message that I got in logs:

2019-04-29 11:14:15.973070+0300 TagReader[4490:1146598] [general] <NSXPCConnection: 0x282e033c0> connection to service named com.apple.nfcd.service.corenfc: Exception caught during decoding of received message, dropping incoming message.
Exception: Exception while decoding argument 0 (#2 of invocation):
Exception: decodeObjectForKey: class "NFFieldNotification" not loaded or does not exist

Any ideas how this can be solved?

Thanks a lot.

**Comment by vinceyuan** [comment]
It depends on what NFC data Android app writes when simulating NFC card. Better use simple and widely used format.
