### ISSUE TITLE
Error when archiving project

### ISSUE THREAD

**Issue by damthieuquang** [vinceyuan/VYNFCKit#14]
When I archived the project, I received the error below:
![Screen Shot 2019-08-12 at 11 07 39 PM](https://user-images.githubusercontent.com/6957056/62879798-2198a600-bd56-11e9-9aa6-8c820e52321d.png)

I don't know why because the error did not appear when I ran it on the simulator and my devices. Hope you fix it

Notice: I get the framework by Carthage.
My test project is using Swift

**Comment by vinceyuan** [comment]
I never use Carthage. It will be great if you can fix it and make a PR. Thanks

**Comment by damthieuquang** [comment]
I tried to fix it for a few days, but I couldn't find any solution for it.
