### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by QuynhNguyen** [vinceyuan/VYNFCKit#3]
Any plan to support Carthage?

**Comment by vinceyuan** [comment]
@QuynhNguyen I don't use Carthage. Welcome to send me a pull request.

**Comment by QuynhNguyen** [comment]
#6 Pull requested

**Comment by vinceyuan** [comment]
@QuynhNguyen Thanks!

**Comment by QuynhNguyen** [comment]
Once you cut a new release, you can add this to the README so people know that you are supporting CARTHAGE

`github "vinceyuan/VYNFCKit" ~> VERSION_NUMBER_HERE`

**Comment by vinceyuan** [comment]
Sure.
