### ISSUE TITLE
Unrecognized attributes in messages shall beignored; they shall not cause the message to be rejected

### ISSUE THREAD

**Issue by Anrufliste** [vinceyuan/VYNFCKit#4]
Hi,

first I like to thank you for your great work. It give me the best starting point to explore WiFi setup by NFC with swift. I used your example with a "Speedport Smart" (router auf Telekom Deutschland GmbH in Germany) and it did not work, so I dig into your code and the specification.

In "Wi-Fi Simple Configuration Technical Specification v2.0.4", Page 100 (Configuration Token - Credential - Data Element Definitions) it stated, that "Note: Unrecognized attributes in messages shall beignored; they shall not cause the message to be rejected."

In "VYNFCNDEFPayloadParser.m" the method  +(nullable VYNFCNDEFWifiSimpleConfigCredential *)parseWifiSimpleConfigCredential:(unsigned char*)payloadBytes length:(NSUInteger)length 

the section for unknown attributes return nil!

A quick (dirty) hack would be, to increment the index by 1 and out-comment the return nil. This way you get ride of unknown attributes with unknown additional information. (As long as those information does not collide with attribute pattern).

You can reduce this risk, by implementing more known attributes to skip those additional information - because the length is known. 

Regards,
Emil

**Comment by vinceyuan** [comment]
Thanks for reporting it. Could you please provide the binary payload like [this](https://github.com/vinceyuan/VYNFCKit/blob/master/VYNFCKitTests/VYNFCKitTestsHelper.m#L91) for me to investigate?

**Comment by vinceyuan** [comment]
@Anrufliste If there is no sample data provided, I can't modify the parsing code. Need to unit test it to make sure the change is correct. Sounds like you already have a solution. You are welcome to make a pull request. See https://github.com/vinceyuan/VYNFCKit#how-to-contribute

**Comment by Anrufliste** [comment]
Hi,

testdata for Payload:

payload.payload = [NSData dataWithBytes:"\x10\x0e\x00\x3e\x10\x26\x00\x01\x01\x10\x45\x00\x0b\x57\x4c\x41\x4e\x2d\x58\x33\x4a\x37\x36\x32\x10\x03\x00\x02\x00\x20\x10\x0f\x00\x02\x00\x08\x10\x27\x00\x10\x31\x33\x35\x38\x34\x35\x35\x32\x32\x39\x30\x34\x33\x33\x32\x35\x10\x20\x00\x06\xc4\xf0\x81\x83\x0a\x14\x10\x0e\x00\x3e\x10\x26\x00\x01\x01\x10\x45\x00\x0b\x57\x4c\x41\x4e\x2d\x58\x33\x4a\x37\x36\x32\x10\x03\x00\x02\x00\x20\x10\x0f\x00\x02\x00\x08\x10\x27\x00\x10\x31\x33\x35\x38\x34\x35\x35\x32\x32\x39\x30\x34\x33\x33\x32\x35\x10\x20\x00\x06\xc4\xf0\x81\x83\x0a\x17" length:132];

This Token / Payload includes two credentials (2,5 and 5 Ghz) wich only differed in the last byte of the mac. The Parser can now only take one of them, but because of an unknown attribute it even does not take it (pull request will come ;-)

100e	//Credential start
003e	// ???
1026	// Network Index
00		// 0
0101	// ???
1045      	// SSID Start
000b      	// SSID-length: 11
574c414e2d58334a373632	// WLAN-X3J762
1003      	// AUTH_TYPE  
0002      	// AUTH_WPA_PERSONAL
0020	// 32
100f         // ENCRYPT_TYPE
0002	// ENCRYPT_WEP 
0008	// 8
1027 // NETWORK_KEY
0010 // Network_key-length: 16 
31333538343535323239303433333235 // 1358455229043325
1020	// MAC_ADDRESS
0006	// Macaddr-length: 6
c4f081830a14// c4:f0:81:83:0a:14
100e	//Credential start
003e	// ???
1026	// Network Index
00		// 0
0101	// ???
1045      	// SSID Start
000b      	// SSID-length: 11
574c414e2d58334a373632	// WLAN-X3J762
1003       // AUTH_TYPE  
0002       // AUTH_WPA_PERSONAL
0020	// 32
100f         // ENCRYPT_TYPE
0002	// ENCRYPT_WEP 
0008	// 8
1027 // NETWORK_KEY
0010 // Network_key-length: 16 
31333538343535323239303433333235 // 1358455229043325
1020 // MAC_ADDRESS
0006 // MacAddr-length: 6
c4f081830a17 // c4:f0:81:83:0a:17

Regards,
Emil

**Comment by Anrufliste** [comment]
Pull Request startet: https://github.com/vinceyuan/VYNFCKit/pull/5

**Comment by vinceyuan** [comment]
Thanks for the test data. I will investigate this issue with it later. The pull request must include unit tests. I can do it.

**Comment by vinceyuan** [comment]
@Anrufliste Solved. Please upgrade to 0.3.0 which supports multiple credentials. Thanks a lot for reporting it and providing test data. 👍

**Comment by vinceyuan** [comment]
@Anrufliste Does 0.3.0 work for you?

**Comment by Anrufliste** [comment]
Hi,

I will check this in the next few days... sorry I am very busy right now, so I cannot work as much on my hobbies as I would like to.

Regards,
Emil

**Comment by Anrufliste** [comment]
Hi 0.3.0 works great, it ignores the unknown attributes as well as parse multiple credentials in one message - greate work, thank you very much.

While searching for the problem, I recordnized that the standard defines many more attributes (which I do not need now) - are you planing to integrate them? Maybe I could make some code for them at the end of the year - if you like.

Regards,
Emil

**Comment by vinceyuan** [comment]
You are right. There are so many more attributes. The most difficult part has been solved. It's easy to support more attributes. But I don't plan to integrate them, simply because I don't have sample data.

It's an open source project. It's great if you can add support to more attributes. Just remember to add unit tests. Thank you.
