### ISSUE TITLE
x-vcard is deprecated

### ISSUE THREAD

**Issue by NickAtGit** [vinceyuan/VYNFCKit#7]
Hi, thanks for your framework, it is very useful. However from Wikipedia I read that x-vcard is a deprecated format. Maybe you can fix that in the future :)

> https://en.wikipedia.org/wiki/VCard
> 
> As of version 4.0 specification, other media types known to have been used previously are now deprecated, including:[1]
> 
> text/x-vcard

**Comment by vinceyuan** [comment]
Thanks for reporting. I used an Android app NFC TagWriter by NXP to write x-vcard into a NFC tag. Though x-vcard format is deprecated in the specification, it probably is still being used. Need to support other vcard formats. Waiting for pull requests 😄
