### ISSUE TITLE
How to send commands？

### ISSUE THREAD

**Issue by BadDeveloper2022** [vinceyuan/VYNFCKit#8]
How to send commands？
Id like to read ID card，Send a command and accept a data

**Comment by vinceyuan** [comment]
"Using Core NFC, you can **read** Near Field Communication (NFC) tags of types 1 through 5 that contain data in the NFC Data Exchange Format (NDEF)."
Read only. You cannot send data via Core NFC. Apple does not open the SDK for writing.

**Comment by BadDeveloper2022** [comment]
OK. Thanks.
Unfortunately.
