### ISSUE TITLE
How can i know last version num?

### ISSUE THREAD

**Issue by vitabr** [vinceyuan/VYNFCKit#9]
Just wondering where to find this missing version info for Carthage file link

**Comment by vinceyuan** [comment]
Sorry I have no idea because I don’t use Carthage. If you know how to fix it, make a PR please. Thanks

**Comment by hangzai123** [comment]
why my iphone can't scan ,my iphone is iphone7,If there is a setting in the iphone NFC functionality,but I can't find it

**Comment by windswrold** [comment]
emm.. my iphone is iphone7 too, can't scan,.
